
name: build-angle

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * 0"
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: windows-2022
    permissions:
      contents: write
      actions: write
      attestations: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        id: build
        shell: cmd
        run: call build.cmd

      #- name: release
      #  id: release
      #  if: steps.build.outputs.ANGLE_COMMIT != ''
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    tag_name: "angle-vulkan-backend"
      #    release_name: "angle-vulkan-backend"
      #    body: |
      #      [angle commit](https://github.com/google/angle/commit/${{ steps.build.outputs.ANGLE_COMMIT }})

      - name: upload
        id: upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./angle/angle-${{ steps.build.outputs.BUILD_DATE }}.zip
            ./angle/angle-src-${{ steps.build.outputs.BUILD_DATE }}.zip
          tag_name: ${{ inputs.tag || github.ref_name }}
          draft: true
          fail_on_unmatched_files: true
